http:
  url: 'http://localhost'
  port: 4004
mongoose:
  id: default
  url: mongodb://localhost/fsd-concept
smtp:
  host: 'smtp.mailtrap.io'
  port: '2525'
  auth: smtp
  sender: '"no-answer" <no-answer@fsd.spec>'